os:
  - linux

language: php

services:
  - mysql

php:
  - '7.3'

before_script:
  - mysql -e 'CREATE DATABASE jezior_cms;'
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - vendor/bin/phpunit
